/*

Custom exception handler for no handler defined in the trigger framework

Class:              NoHandlerException
Date:               03/24/2014
Version:            1
Last Updated:       03/24/2014
    *   Stubbed / Completed

////////////////////////////////////////////////////////////////////////////////
*/

global class NoHandlerException extends Exception
{
  // -------- Constants --------
  // None
  
  // -------- Constructor --------
    // Parent
    
    // -------- Variables --------
  // None
  
  // -------- Properties --------
  // None
  
  // -------- Methods --------
  // None
  
  // -------- Internal Classes --------
  // None
}