@isTest
global class PlateauCryptoMockService2 implements WebserviceMock {
    
    global void doInvoke (
        Object stub,
        Object request,
        Map<String, Object> response,
        String endpoint,
        String soapAction,
        String requestName,
        String responseNS,
        String responseName,
        String responseType) {/*
           PlateauCrypto.encryptIDOnlyWithURLEncodeResponse respElement = new PlateauCrypto.encryptIDOnlyWithURLEncodeResponse();
            response.put('response_x', respElement);*/
   }

}