/**************************************************
** PR- 01923
**Created By- Harsh Mathur
**Created On- June 17 2009
**Last Modified- 
**Last Modified On-
**Desciption- Test class for controller PlateauCrypto
*****************************************************/
@isTest
public class TestPlateauCrypto{/*
    @isTest
    public static void checkPlateauCrypto1(){
        Test.startTest();
        Test.setMock(WebServiceMock.class, new PlateauCryptoMockService());
        
        PlateauCrypto platCryObj = new PlateauCrypto();
        PlateauCrypto.SunpowerCryptoServicePort sunCrySerObj = new PlateauCrypto.SunpowerCryptoServicePort();
        sunCrySerObj.encryptWithReturnLiveURL('test', 'test'); 
        
        Test.stopTest();
    }
    
    @isTest
    public static void checkPlateauCrypto2(){
        Test.startTest();
        Test.setMock(WebServiceMock.class, new PlateauCryptoMockService2());
        
        PlateauCrypto platCryObj = new PlateauCrypto();
        PlateauCrypto.SunpowerCryptoServicePort sunCrySerObj = new PlateauCrypto.SunpowerCryptoServicePort();    
        sunCrySerObj.encryptIDOnlyWithURLEncode('test', 'test');
        
        Test.stopTest();
    }
    
    public static testMethod void checkPlateauCrypto3(){
        Test.startTest();
        Test.setMock(WebServiceMock.class, new PlateauCryptoMockService());
        
        PlateauCrypto platCryObj = new PlateauCrypto();
        PlateauCrypto.encryptWithReturnLiveURLResponse obj1 = new PlateauCrypto.encryptWithReturnLiveURLResponse();
        PlateauCrypto.encryptIDOnlyWithURLEncodeResponse obj2 = new PlateauCrypto.encryptIDOnlyWithURLEncodeResponse();
        
        Test.stopTest();
    }*/
}