@isTest(seeAllData=true)
private class Testpartnerportalloginfortesting{
    /*

    //Test Method for code coverage of partnerportalSiteLoginController
    static testmethod void testpartnerportallogin() {
    
        PageReference pageRef = Page.partnerportalloginfortesting;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getHeaders().put('Accept-Language','en-US'); 
        System.debug('CurrentPage Headers -----'+ApexPages.currentPage().getHeaders());
        partnerportalloginfortestingController ppsl = new partnerportalloginfortestingController ();
        ppsl.username = 'test@salesforce.com';
        ppsl.password = '123456';
        System.assertEquals(ppsl.login(),null);
        ppsl.authCurrentUser();
        ApexPages.currentPage().getParameters().put('startURL','/home/home.jsp');
        ppsl.login();
    }*/ 
}